---

- hosts: 127.0.0.1
  connection: local

  vars:
    brew_pkgs:
      - asdf
      - grep
      - docker
      - docker-compose
      - colima

    cask_pkgs:
      - amethyst
      - brave-browser
      - visual-studio-code
      - 1password
      - warp

  tasks:

    - name: Install brew packages
      community.general.homebrew:
        name: "{{ brew_pkgs }}"
        state: present
        update_homebrew: true

    - name: Install cask packages
      community.general.homebrew_cask:
        name: "{{ cask_pkgs }}"
        state: present

    - name: Add .macos file
      template:
        src: dotmacos.j2
        dest: ~/.macos
        owner: "{{ lookup('env', 'USER') }}"
        mode: 0644



    
    # - name: Install asdf packages
